Feat/add particular clicks event
cloudcar-app/analytic-tool pull request #1
Opened 2022-01-18 15:41 UTC by vicentevegaulloa

## What?
Se le añadió el evento _particular clicks_ a la librería. Además se cambió la forma de usar el config para que se ocupe un config propio de cada proyecto que linstale _analytic-tool_.

## Why?
Esto permite saber que elementos de la página el usuario clickea. Además, la configuración permite añadir definir los selectores de los elementos que nos interesan. 

## How?
En el index se revisa si existe una configuración para el evento. De haberla, se le entrega a la función `trackParticularClicks` la cual envía un post request al collector cada vez que el usuario clickea un elemento de interés.

## Testing?
La forma de testear fue definiendo los selectores de los elementos de interés en la config y revisando si con cada click los eventos llegaban al final del pipeline de snowplow.

## Screenshots

## Anything Else?
Los datos que se envían dependen de un schema que está por actualizarse para adaptarse a los futuros usos de los datos, por lo que es recomendable ignorar los datos que se envían en el post en caso de no entenderse.

2022-01-19 15:29 UTC, adisrael requested changes
Dejé unos comentarios de orden principalmente.

Sería bueno documentar la librería, al menos los aspectos más relevantes en el README.

2022-01-19 15:29 UTC, adisrael commented on lib/config/configTypes.ts
> +}
Sería bueno agregar saltos de línea entre cada definición para dejar el archivo ordenado.
Creo también que sería bueno tomar una convención para ordenar los tipos (podría ser orden alfabético). Así será más fácil encontrar los tipos cuando este archivo empiece a crecer y también mejorará el control de cambios con git.

2022-01-19 15:29 UTC, adisrael commented on lib/index.ts
> +  }
mantener indentación ordenada y agregar un salto de línea entre imports y la declaración

2022-01-19 15:29 UTC, adisrael commented on package.json
> +    "app-root-path": "^3.0.0",
Esta librería se está ocupando? No la vi entre los archivos cambiados.
Si no se está usando, sería bueno quitarla.

2022-01-19 19:55 UTC, adisrael approved these changes

2022-01-19 20:01 UTC, merged

2022-01-19 22:20 UTC, pdecarcer commented on lib/config/configTypes.ts
> +}
En estricto rigor para una libreria se deberian de definir types mas que interface

2022-01-19 22:21 UTC, pdecarcer commented on lib/custom_trackers/particular_clicks.ts
> +    console.log(error);
Para esto podriamos configurar un logger externo que nos indique si falla

2022-01-19 22:24 UTC, pdecarcer commented on lib/custom_trackers/particular_clicks.ts
> +      });
en general traten de utilizar nombres mas descriptivos
`el: Element` => `element: Element`
`ev: Event` => `event: Event`

2022-01-19 22:24 UTC, pdecarcer commented on lib/index.ts
>          sessionCookieTimeout: 3600,
Eso esta en dias, horas, segundos?

2022-01-19 22:25 UTC, pdecarcer commented on lib/tools/generateJson.ts
> +          schema: 'iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0',
Esa schema tiene que ser de snowplow o la podemos crear nosotros?

2022-01-19 22:26 UTC, pdecarcer reviewed
Esta buena, les deje un par de comentarios para considerar más adelante

2022-01-20 13:03 UTC, vicentevegaulloa commented on lib/custom_trackers/particular_clicks.ts
> +    console.log(error);
Lo agregaré al final del sprint para que no se nos olvide

2022-01-20 13:09 UTC, vicentevegaulloa commented on lib/index.ts
>          sessionCookieTimeout: 3600,
En segundos, dejaré un comentario al lado

2022-01-20 13:14 UTC, vicentevegaulloa commented on lib/tools/generateJson.ts
> +          schema: 'iglu:com.snowplowanalytics.snowplow/unstruct_event/jsonschema/1-0-0',
Ese es el evento que encapsula a todos los eventos custom. Supongo que podríamos crearlo nosotros pero eso significaría meter mano en iglu y en el código(no config) del enrichment de validación, y lo último no creo que sea tan fácil de hacer. Si quisieramos no incluir datos del schema o agregar nuevos podríamos simplemente ignorar campos o agregar esos datos en el schema custom.