Feat/add mail decryption
cloudcar-app/analytic-tool pull request #13
Opened 2022-02-01 19:05 UTC by vicentevegaulloa

## What?
Se agregó la funcinalidad de añadir el correo electrónico del usuario a los eventos.
## Why?
Este funcionalidad fue agregada, ya que es importante para identificar un usuario en particular, saber su recorrido y los eventos que gatilla al estar en contacto con la página. Esto es parte de un proceso que permitirá saber que dispositivos pertenecen al mismo usuario.
## How?
Esta funcionalidad se realizó creando una cookie llamada ´userMail´, la que contiene el correo del usuario (puede estar vacia o no dependiendo si el correo se encuentra hasheado en el url). Esta cookie es tomada por el schema de los eventos y es enviada al a través del context. De manera que todos los eventos gatillados por un usuario quedarán asociados a su email.
## Testing? (almost required)
Se testeó mirando si los eventos llegaban a la base de datos con el correo del usuario asociado.
## Screenshots (almost required in frontend)
## Anything Else? (optional)

2022-02-02 16:47 UTC, martinluna commented on lib/tools/cookieUserMail.ts
> +export function cookieUserMail() {
Siento que el nombre del archivo/función no es tan claro. Lo cambiaría por `setUserMailCookie`.

2022-02-02 16:49 UTC, martinluna requested changes

2022-02-02 16:49 UTC, martinluna commented on lib/tools/cookieUserMail.ts
> +export function cookieUserMail() {
Siento que el nombre del archivo/función no es tan claro. Lo cambiaría por `setUserMailCookie` o algo que describa mejor que se está haciendo.

2022-02-02 16:49 UTC, martinluna commented on lib/tools/cookieManagement.ts
> +const checkCookie = (cookieName:string) => {
cambiaría el nombre de esta función por `checkIfdCookieExists`

2022-02-02 16:49 UTC, martinluna commented on lib/tools/cookieManagement.ts
> +const createCookie = (key:string, value:string, expirationDay:number)=> {
Me parece que el nombre de este módulo debería ser `cookieManager` o algo del estilo.

2022-02-03 15:44 UTC, pdecarcer approved these changes

2022-02-03 16:06 UTC, merged